apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lez4sxjfd-python 
  janus-idp.io/tekton: lez4sxjfd-python
  backstage.io/kubernetes-id: lez4sxjfd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lez4sxjfd-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  